/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
extern crate time;
use time::PreciseTime;

fn main() {
    let start = PreciseTime::now();
    println!("Sum of even fib numbers: {}",fib_even_sum(34));
    let end = PreciseTime::now();
    println!("Used: {} seconds", start.to(end));
}

fn fib_even_sum(x:usize) -> u64{
        const X: usize = 93;// u64 does not fitt a bigger fib number than fib(93)
        let mut array: [u64; X] = [0; X];
        let mut sum: u64 = 0;
        array[0] = 1;
        array[1] = 1;
        for i in 2..x {
            array[i] = array[i - 1] + array[i - 2];
            if array[i] - (2*(array[i]/2)) == 0{
                sum += array[i];
            }
        }
        return sum;
}
